import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import multer from 'multer';
import {Pool} from 'pg';
import {randomUUID} from 'crypto';
import {v2 as cloudinary} from 'cloudinary';

const app=express();
const PORT=Number(process.env.PORT||10000);
const JWT_SECRET=process.env.JWT_SECRET;
if(!JWT_SECRET) console.warn('WARNING: JWT_SECRET is not configured. Set it in Render.');
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('localhost')?false:{rejectUnauthorized:false},max:10});
const q=(text,params=[])=>pool.query(text,params); const uid=()=>randomUUID(); const s=v=>v==null?'':String(v).trim(); const arr=v=>Array.isArray(v)?v:(typeof v==='string'&&v.trim()?v.split(',').map(x=>x.trim()).filter(Boolean):[]);
const adminRoles=new Set(['admin','owner','superadmin']);
const isAdmin=u=>adminRoles.has(String(u?.role||'').toLowerCase());
const json=v=>{try{return typeof v==='string'?JSON.parse(v):(v??{});}catch{return v??{};}};
app.use(helmet({crossOriginResourcePolicy:false}));
const origins=(process.env.FRONTEND_ORIGIN||'').split(',').map(s).filter(Boolean);
app.use(cors({origin:(origin,cb)=>{if(!origin||!origins.length||origins.includes(origin))return cb(null,true);cb(new Error('CORS origin not allowed'));},credentials:true,methods:['GET','POST','PUT','PATCH','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization']}));
app.use(express.json({limit:'12mb'})); app.use(express.urlencoded({extended:true,limit:'12mb'})); app.use(morgan('combined'));
app.use((req,res,next)=>{res.setHeader('Cache-Control','no-store');next();});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024}});
function sign(u){return jwt.sign({id:u.id,email:u.email,role:u.role},JWT_SECRET||'unsafe-dev-secret',{expiresIn:'30d'});}
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),JWT_SECRET||'unsafe-dev-secret');next();}catch{res.status(401).json({error:'Authentication required'});}}
function requireAdmin(req,res,next){auth(req,res,()=>isAdmin(req.user)?next():res.status(403).json({error:'Admin only'}));}
function err(res,e,status=500){console.error(e);res.status(status).json({error:e?.message||'Server error'});}
async function userById(id){const r=await q('SELECT id,email,name,role,avatar,created_at,updated_at FROM users WHERE id=$1',[id]);return r.rows[0]||null;}
function publicUser(u){return u&&{id:u.id,email:u.email,name:u.name||'',role:u.role,avatar:u.avatar||null,created_at:u.created_at};}

app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');res.json({ok:true,service:'zhuomarket-backend',version:'3.0.0',database:'connected'})}catch(e){err(res,e,503)}});

// AUTH
app.post('/api/auth/register',async(req,res)=>{try{const email=s(req.body.email||req.body.gmail).toLowerCase(),password=String(req.body.password||'');if(!email||!password)return res.status(400).json({error:'Email and password required'});if(password.length<6)return res.status(400).json({error:'Password must be at least 6 characters'});if(req.body.confirmPassword!=null&&password!==String(req.body.confirmPassword))return res.status(400).json({error:'Passwords do not match'});if((await q('SELECT 1 FROM users WHERE lower(email)=lower($1)',[email])).rowCount)return res.status(409).json({error:'Email already registered'});const u={id:uid(),email,password_hash:await bcrypt.hash(password,12),name:s(req.body.name)||email.split('@')[0],role:'client'};await q('INSERT INTO users(id,email,password_hash,name,role) VALUES($1,$2,$3,$4,$5)',[u.id,u.email,u.password_hash,u.name,u.role]);res.status(201).json({token:sign(u),user:publicUser(u)})}catch(e){err(res,e)}});
app.post('/api/auth/login',async(req,res)=>{try{const email=s(req.body.email||req.body.gmail).toLowerCase(),password=String(req.body.password||'');const r=await q('SELECT * FROM users WHERE lower(email)=lower($1)',[email]);if(!r.rowCount||!(await bcrypt.compare(password,r.rows[0].password_hash)))return res.status(401).json({error:'Invalid email or password'});res.json({token:sign(r.rows[0]),user:publicUser(r.rows[0])})}catch(e){err(res,e)}});
app.get('/api/auth/me',auth,async(req,res)=>{try{const u=await userById(req.user.id);if(!u)return res.status(404).json({error:'User not found'});res.json({user:u})}catch(e){err(res,e)}});
app.patch('/api/auth/me',auth,async(req,res)=>{try{const name=req.body.name===undefined?null:s(req.body.name);const avatar=req.body.avatar??req.body.photoUrl??req.body.photo??req.body.image;const r=await q('UPDATE users SET name=COALESCE($2,name),avatar=COALESCE($3,avatar),updated_at=now() WHERE id=$1 RETURNING id,email,name,role,avatar,created_at,updated_at',[req.user.id,name,avatar==null?null:s(avatar)]);res.json({user:r.rows[0]})}catch(e){err(res,e)}});
app.put('/api/auth/me',(req,res,next)=>{if(req.headers.authorization)return next();return res.status(401).json({error:'Authentication required'})},auth,async(req,res)=>{try{const r=await q('UPDATE users SET name=COALESCE($2,name),avatar=COALESCE($3,avatar),updated_at=now() WHERE id=$1 RETURNING id,email,name,role,avatar,created_at,updated_at',[req.user.id,req.body.name===undefined?null:s(req.body.name),s(req.body.avatar??req.body.photoUrl??req.body.photo??req.body.image)]);res.json({user:r.rows[0]})}catch(e){err(res,e)}});
app.post('/api/auth/logout',auth,(req,res)=>res.json({ok:true})); app.post('/api/auth/refresh',auth,async(req,res)=>{const u=await userById(req.user.id);if(!u)return res.status(404).json({error:'User not found'});res.json({token:sign(u),user:u})});

// UPLOADS: persistent Cloudinary, never fake base64.
if(process.env.CLOUDINARY_CLOUD_NAME&&process.env.CLOUDINARY_API_KEY&&process.env.CLOUDINARY_API_SECRET) cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET,secure:true});
app.post('/api/uploads',auth,upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'No file uploaded'});if(!process.env.CLOUDINARY_CLOUD_NAME)return res.status(503).json({error:'Image storage is not configured. Add Cloudinary environment variables.'});const result=await new Promise((resolve,reject)=>{const st=cloudinary.uploader.upload_stream({folder:process.env.CLOUDINARY_FOLDER||'zhuomarket',resource_type:'image'},(e,r)=>e?reject(e):resolve(r));st.end(req.file.buffer);});res.status(201).json({url:result.secure_url,image:result.secure_url,imageUrl:result.secure_url,fileUrl:result.secure_url,publicId:result.public_id})}catch(e){err(res,e)}});

// PRODUCTS
function productOut(p){return {...p,oldPrice:Number(p.old_price||0),quantity:p.quantity??p.stock,images:json(p.images)||[],storage:json(p.storage)||[],colors:json(p.colors)||[],specifications:json(p.specifications)||{},status:p.active?'published':'draft',published:p.published!==false};}
app.get('/api/products',async(req,res)=>{try{const r=await q('SELECT * FROM products WHERE active=true AND published=true AND stock>0 ORDER BY created_at DESC');const products=r.rows.map(productOut);res.json({products,data:products})}catch(e){err(res,e)}});
app.get('/api/brands',async(req,res)=>{try{const r=await q("SELECT DISTINCT brand FROM products WHERE active=true AND published=true AND brand<>'' ORDER BY brand");const brands=r.rows.map(x=>x.brand);res.json({brands,data:brands})}catch(e){err(res,e)}});
function productBody(b){const stock=Math.max(0,Number(b.stock??b.quantity??0)||0);return {name:s(b.name||b.model||b.title)||'Produit',brand:s(b.brand),category:s(b.category)||'Téléphone',price:Number(b.price)||0,oldPrice:Number(b.oldPrice??b.old_price)||0,discount:Number(b.discount)||0,currency:s(b.currency)||'USD',stock,quantity:stock,image:s(b.image||b.imageUrl),images:arr(b.images||b.image),description:s(b.description),storage:arr(b.storage),colors:arr(b.colors),specifications:b.specifications&&typeof b.specifications==='object'?b.specifications:{},active:b.active!==false&&String(b.status||'published').toLowerCase()!=='draft',published:b.published!==false&&String(b.status||'published').toLowerCase()!=='draft'};}
app.post('/api/products',requireAdmin,async(req,res)=>{try{const b=productBody(req.body);if(b.price<=0)return res.status(400).json({error:'Price must be greater than 0'});const r=await q(`INSERT INTO products(id,name,brand,category,price,old_price,discount,currency,stock,quantity,image,images,description,storage,colors,specifications,active,published,seller_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) RETURNING *`,[uid(),b.name,b.brand,b.category,b.price,b.oldPrice,b.discount,b.currency,b.stock,b.image,JSON.stringify(b.images),b.description,JSON.stringify(b.storage),JSON.stringify(b.colors),JSON.stringify(b.specifications),b.active,b.published,req.user.id]);res.status(201).json({product:productOut(r.rows[0])})}catch(e){err(res,e,400)}});
app.put('/api/products/:id',requireAdmin,async(req,res)=>{try{const b=productBody(req.body);const r=await q(`UPDATE products SET name=$2,brand=$3,category=$4,price=$5,old_price=$6,discount=$7,currency=$8,stock=$9,quantity=$9,image=$10,images=$11,description=$12,storage=$13,colors=$14,specifications=$15,active=$16,published=$17,updated_at=now() WHERE id=$1 RETURNING *`,[req.params.id,b.name,b.brand,b.category,b.price,b.oldPrice,b.discount,b.currency,b.stock,b.image,JSON.stringify(b.images),b.description,JSON.stringify(b.storage),JSON.stringify(b.colors),JSON.stringify(b.specifications),b.active,b.published]);if(!r.rowCount)return res.status(404).json({error:'Product not found'});res.json({product:productOut(r.rows[0])})}catch(e){err(res,e,400)}});
app.patch('/api/products/:id',requireAdmin,async(req,res)=>{req.body={...req.body,...(req.body.quantity!==undefined?{stock:req.body.quantity}:{}),...(req.body.status!==undefined?{active:req.body.status!=='draft',published:req.body.status!=='draft'}:{})};return app._router.handle({...req,method:'PUT',url:'/api/products/'+req.params.id},res,()=>{});});
app.delete('/api/products/:id',requireAdmin,async(req,res)=>{try{const r=await q('UPDATE products SET active=false,published=false,updated_at=now() WHERE id=$1 RETURNING id',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Product not found'});res.json({ok:true})}catch(e){err(res,e)}});

// PROMOTIONS
function promoOut(p){return {...p,oldPrice:Number(p.old_price||0),price:Number(p.price||0),discount:Number(p.discount||0),productId:p.product_id,images:json(p.images)||[],status:p.active?'published':'draft'};}
app.get('/api/promotions',async(req,res)=>{try{const r=await q('SELECT * FROM promotions WHERE active=true ORDER BY created_at DESC');const promotions=r.rows.map(promoOut);res.json({promotions,data:promotions})}catch(e){err(res,e)}});
function promoBody(b){return {title:s(b.title||b.name),description:s(b.description),price:Number(b.price)||0,oldPrice:Number(b.oldPrice??b.old_price)||0,discount:Number(b.discount)||0,image:s(b.image||b.imageUrl),images:arr(b.images||b.image),productId:b.productId||b.product_id||null,active:b.active!==false&&String(b.status||'published').toLowerCase()!=='draft',status:s(b.status)||'published'};}
async function createPromo(req,res){try{const b=promoBody(req.body);const r=await q(`INSERT INTO promotions(id,title,description,price,old_price,discount,image,images,product_id,active,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[uid(),b.title,b.description,b.price,b.oldPrice,b.discount,b.image,JSON.stringify(b.images),b.productId,b.active,b.status]);res.status(201).json({promotion:promoOut(r.rows[0])})}catch(e){err(res,e,400)}}
app.post('/api/promotions',requireAdmin,createPromo); app.post('/api/admin/promotions',requireAdmin,createPromo);
async function updatePromo(req,res){try{const b=promoBody(req.body);const r=await q(`UPDATE promotions SET title=$2,description=$3,price=$4,old_price=$5,discount=$6,image=$7,images=$8,product_id=$9,active=$10,status=$11,updated_at=now() WHERE id=$1 RETURNING *`,[req.params.id,b.title,b.description,b.price,b.oldPrice,b.discount,b.image,JSON.stringify(b.images),b.productId,b.active,b.status]);if(!r.rowCount)return res.status(404).json({error:'Promotion not found'});res.json({promotion:promoOut(r.rows[0])})}catch(e){err(res,e,400)}}
app.put('/api/promotions/:id',requireAdmin,updatePromo);app.patch('/api/promotions/:id',requireAdmin,async(req,res)=>{if(Object.keys(req.body||{}).length===1&&req.body.status!==undefined){const active=String(req.body.status).toLowerCase()!=='draft'&&String(req.body.status).toLowerCase()!=='off'&&req.body.status!==false;const r=await q('UPDATE promotions SET active=$2,status=$3,updated_at=now() WHERE id=$1 RETURNING *',[req.params.id,active,active?'published':'draft']);if(!r.rowCount)return res.status(404).json({error:'Promotion not found'});return res.json({promotion:promoOut(r.rows[0])});}return updatePromo(req,res)});
app.delete('/api/promotions/:id',requireAdmin,async(req,res)=>{const r=await q('UPDATE promotions SET active=false,status=\'deleted\',updated_at=now() WHERE id=$1 RETURNING id',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Promotion not found'});res.json({ok:true})});
app.delete('/api/admin/promotions/:id',requireAdmin,async(req,res)=>{const r=await q('UPDATE promotions SET active=false,status=\'deleted\',updated_at=now() WHERE id=$1 RETURNING id',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Promotion not found'});res.json({ok:true})});

// PAYMENT METHODS
function pmOut(p){return {...p,name:p.name||p.provider,transferNumber:p.transfer_number,accountNumber:p.account_number,accountName:p.account_name,accountEmail:p.account_email,handle:p.handle,paymentUrl:p.payment_url,enabled:p.active};}
app.get('/api/payment-methods',async(req,res)=>{try{const r=await q('SELECT * FROM payment_methods WHERE active=true ORDER BY created_at');const data=r.rows.map(pmOut);res.json({paymentMethods:data,data})}catch(e){err(res,e)}});
app.get('/api/admin/payment-methods',requireAdmin,async(req,res)=>{try{const r=await q('SELECT * FROM payment_methods ORDER BY created_at');const data=r.rows.map(pmOut);res.json({paymentMethods:data,data})}catch(e){err(res,e)}});
function pmBody(b){return {provider:s(b.provider||b.name)||'Manual',name:s(b.name||b.provider),description:s(b.description),instructions:s(b.instructions||b.publicInfo||b.paymentInfo),transferNumber:s(b.transferNumber||b.transfer_number||b.phone||b.number),accountNumber:s(b.accountNumber||b.account_number),accountName:s(b.accountName||b.account_name),accountEmail:s(b.accountEmail||b.account_email||b.email),handle:s(b.handle||b.username),paymentUrl:s(b.paymentUrl||b.payment_url||b.checkoutUrl||b.checkout_url),active:b.active!==undefined?Boolean(b.active):b.enabled!==undefined?Boolean(b.enabled):true};}
app.post('/api/admin/payment-methods',requireAdmin,async(req,res)=>{try{const b=pmBody(req.body),r=await q('INSERT INTO payment_methods(id,provider,name,description,instructions,transfer_number,account_number,account_name,account_email,handle,payment_url,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *',[uid(),b.provider,b.name,b.description,b.instructions,b.transferNumber,b.accountNumber,b.accountName,b.accountEmail,b.handle,b.paymentUrl,b.active]);res.status(201).json({paymentMethod:pmOut(r.rows[0])})}catch(e){err(res,e,400)}});
app.patch('/api/admin/payment-methods/:id',requireAdmin,async(req,res)=>{try{const b=pmBody(req.body),r=await q('UPDATE payment_methods SET provider=$2,name=$3,description=$4,instructions=$5,transfer_number=$6,account_number=$7,account_name=$8,account_email=$9,handle=$10,payment_url=$11,active=$12,updated_at=now() WHERE id=$1 RETURNING *',[req.params.id,b.provider,b.name,b.description,b.instructions,b.transferNumber,b.accountNumber,b.accountName,b.accountEmail,b.handle,b.paymentUrl,b.active]);if(!r.rowCount)return res.status(404).json({error:'Payment method not found'});res.json({paymentMethod:pmOut(r.rows[0])})}catch(e){err(res,e,400)}});
app.delete('/api/admin/payment-methods/:id',requireAdmin,async(req,res)=>{const r=await q('DELETE FROM payment_methods WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Payment method not found'});res.json({ok:true})});

// ORDERS / REAL MANUAL PAYMENTS
async function cartPriced(client,items){if(!Array.isArray(items)||!items.length)throw new Error('Cart is empty');const cleanItems=items.map(x=>({productId:x.productId||x.id,quantity:Math.max(1,parseInt(x.quantity||x.qty||1,10)),storage:x.storage||null,color:x.color||null}));const ids=[...new Set(cleanItems.map(x=>x.productId).filter(Boolean))];const r=await client.query('SELECT * FROM products WHERE id=ANY($1::uuid[]) AND active=true AND published=true',[ids]);const map=new Map(r.rows.map(p=>[String(p.id),p]));if(map.size!==ids.length)throw new Error('One or more products are unavailable');let total=0,currency=r.rows[0]?.currency||'USD';const out=cleanItems.map(x=>{const p=map.get(String(x.productId));if(Number(p.stock)<x.quantity)throw new Error(`Insufficient stock for ${p.name}`);const unit=Number(p.price);total+=unit*x.quantity;return {productId:p.id,quantity:x.quantity,name:p.name,brand:p.brand,image:p.image,unitPrice:unit,currency:p.currency,storage:x.storage,color:x.color};});return {out,total,currency};}
app.post('/api/orders',auth,async(req,res)=>{const c=await pool.connect();try{await c.query('BEGIN');const {out,total,currency}=await cartPriced(c,req.body.items);const method=s(req.body.paymentMethod),reference=s(req.body.transactionReference||req.body.payment_reference);const oid=uid();await c.query('INSERT INTO orders(id,customer_id,items,total,currency,payment_method,payment_status,status,transaction_reference) VALUES($1,$2,$3,$4,$5,$6,\'pending\',\'En attente\',$7)',[oid,req.user.id,JSON.stringify(out),total,currency,method,reference||null]);if(reference){await c.query('INSERT INTO payments(id,order_id,customer_id,payment_method,amount,currency,transaction_reference,status) VALUES($1,$2,$3,$4,$5,$6,$7,\'pending\')',[uid(),oid,req.user.id,method||'manual',total,currency,reference]);}await c.query('COMMIT');res.status(201).json({order:{id:oid,customerId:req.user.id,items:out,total,currency,paymentMethod:method,paymentStatus:'pending',status:'En attente',transactionReference:reference||null},message:'Payment pending verification'});}catch(e){await c.query('ROLLBACK').catch(()=>{});err(res,e,400)}finally{c.release();}});
function orderOut(o){return {...o,amount:Number(o.total),customerId:o.customer_id,paymentStatus:o.payment_status,transactionReference:o.transaction_reference,items:json(o.items)||[]};}
app.get('/api/orders',auth,async(req,res)=>{try{const r=isAdmin(req.user)&&req.query.admin==='true'?await q('SELECT o.*,u.name,u.email FROM orders o JOIN users u ON u.id=o.customer_id ORDER BY o.created_at DESC'):await q('SELECT * FROM orders WHERE customer_id=$1 ORDER BY created_at DESC',[req.user.id]);const orders=r.rows.map(orderOut);res.json({orders,data:orders})}catch(e){err(res,e)}});
app.patch('/api/orders/:id',auth,async(req,res)=>{try{const r=await q('UPDATE orders SET status=$2,updated_at=now() WHERE id=$1 AND ($3=true OR customer_id=$4) RETURNING *',[req.params.id,s(req.body.status)||'En attente',isAdmin(req.user),req.user.id]);if(!r.rowCount)return res.status(404).json({error:'Order not found'});res.json({order:orderOut(r.rows[0])})}catch(e){err(res,e)}});
app.patch('/api/orders/:id/status',auth,async(req,res)=>{req.body={status:req.body.status};return app._router.handle({...req,method:'PATCH',url:'/api/orders/'+req.params.id},res,()=>{})});
app.patch('/api/orders/:id/payment',requireAdmin,async(req,res)=>{try{const status=s(req.body.status)||'pending';const c=await pool.connect();await c.query('BEGIN');const r=await c.query('UPDATE orders SET payment_status=$2,updated_at=now() WHERE id=$1 RETURNING *',[req.params.id,status]);if(!r.rowCount)throw new Error('Order not found');if(status==='paid'){const items=json(r.rows[0].items)||[];for(const item of items){const sr=await c.query('UPDATE products SET stock=stock-$2,quantity=stock-$2,updated_at=now() WHERE id=$1 AND stock >= $2',[item.productId,Number(item.quantity)||1]);if(!sr.rowCount)throw new Error('Stock changed; cannot confirm payment.');}await c.query('UPDATE payments SET status=\'paid\',verified_at=now(),verified_by=$2 WHERE order_id=$1 AND status=\'pending\'',[req.params.id,req.user.id]);}else if(status==='rejected')await c.query('UPDATE payments SET status=\'rejected\',verified_at=now(),verified_by=$2 WHERE order_id=$1 AND status=\'pending\'',[req.params.id,req.user.id]);await c.query('COMMIT');res.json({order:orderOut(r.rows[0]),ok:true});}catch(e){err(res,e,400)}finally{}});
app.post('/api/orders/:id/payment-confirmation',auth,async(req,res)=>{try{const r=await q('UPDATE orders SET payment_status=\'pending\',updated_at=now() WHERE id=$1 AND customer_id=$2 RETURNING *',[req.params.id,req.user.id]);if(!r.rowCount)return res.status(404).json({error:'Order not found'});res.json({ok:true,order:orderOut(r.rows[0]),message:'Payment pending verification'})}catch(e){err(res,e)}});

// ADMIN USERS / STATS
app.get('/api/users',requireAdmin,async(req,res)=>{const r=await q('SELECT id,email,name,role,avatar,created_at FROM users ORDER BY created_at DESC');res.json({users:r.rows,data:r.rows})});
app.get('/api/admin/users',requireAdmin,async(req,res)=>{const r=await q('SELECT id,email,name,role,avatar,created_at FROM users ORDER BY created_at DESC');res.json({users:r.rows,data:r.rows})});
app.patch('/api/admin/users/:id',requireAdmin,async(req,res)=>{try{const target=await userById(req.params.id);if(!target)return res.status(404).json({error:'User not found'});if(target.role==='owner')return res.status(403).json({error:'The primary Owner cannot be removed or changed'});if(String(req.body.role).toLowerCase()==='owner')return res.status(403).json({error:'Owner role is protected'});const role=String(req.body.role||'client').toLowerCase()==='admin'?'admin':'client';const r=await q('UPDATE users SET role=$2,updated_at=now() WHERE id=$1 RETURNING id,email,name,role,avatar,created_at',[req.params.id,role]);res.json({user:r.rows[0]})}catch(e){err(res,e,400)}});
app.get('/api/admin/stats',requireAdmin,async(req,res)=>{try{const [sales,orders,users,products,pending]=await Promise.all([q("SELECT COALESCE(SUM(total),0) v FROM orders WHERE payment_status='paid'"),q('SELECT COUNT(*) v FROM orders'),q('SELECT COUNT(*) v FROM users'),q('SELECT COUNT(*) v FROM products WHERE active=true'),q("SELECT COUNT(*) v FROM payments WHERE status='pending'")]);const stats={totalSales:Number(sales.rows[0].v),revenue:Number(sales.rows[0].v),ordersCount:Number(orders.rows[0].v),usersCount:Number(users.rows[0].v),productsCount:Number(products.rows[0].v),pendingPayments:Number(pending.rows[0].v),dailySales:[]};res.json({stats,data:stats})}catch(e){err(res,e)}});
app.get('/api/admin/payments',requireAdmin,async(req,res)=>{const status=s(req.query.status);const r=await q(`SELECT p.*,o.items,o.total,o.status order_status,u.name,u.email FROM payments p JOIN orders o ON o.id=p.order_id JOIN users u ON u.id=p.customer_id ${status?'WHERE p.status=$1':''} ORDER BY p.created_at DESC`,status?[status]:[]);res.json({payments:r.rows,data:r.rows})});
app.patch('/api/admin/payments/:id',requireAdmin,async(req,res)=>{const status=s(req.body.status)||'pending';const p=await q('SELECT order_id FROM payments WHERE id=$1',[req.params.id]);if(!p.rowCount)return res.status(404).json({error:'Payment not found'});const r=await q('UPDATE payments SET status=$2,verified_at=now(),verified_by=$3,rejection_reason=$4 WHERE id=$1 RETURNING *',[req.params.id,status,req.user.id,s(req.body.rejectionReason)]);if(status==='paid')await q('UPDATE orders SET payment_status=\'paid\',updated_at=now() WHERE id=$1',[p.rows[0].order_id]);if(status==='rejected')await q('UPDATE orders SET payment_status=\'rejected\',updated_at=now() WHERE id=$1',[p.rows[0].order_id]);res.json({payment:r.rows[0],ok:true})});

// NOTIFICATIONS
async function notify(userId,title,body,type='info'){if(!userId)return;await q('INSERT INTO notifications(id,user_id,title,body,type) VALUES($1,$2,$3,$4,$5)',[uid(),userId,title,body,type]).catch(console.error);}
app.get('/api/notifications',auth,async(req,res)=>{const r=await q('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100',[req.user.id]);res.json({notifications:r.rows,unread:r.rows.filter(x=>!x.read).length,data:r.rows})});
app.patch('/api/notifications/:id/read',auth,async(req,res)=>{const r=await q('UPDATE notifications SET read=true WHERE id=$1 AND user_id=$2 RETURNING *',[req.params.id,req.user.id]);if(!r.rowCount)return res.status(404).json({error:'Notification not found'});res.json({notification:r.rows[0]})});
app.post('/api/notifications/mark-all-read',auth,async(req,res)=>{await q('UPDATE notifications SET read=true WHERE user_id=$1',[req.user.id]);res.json({ok:true})});
app.post('/api/notifications/due-reminders',auth,async(req,res)=>{res.json({ok:true,created:0,notifications:[]})});
app.get('/api/notification-preferences',auth,async(req,res)=>{const r=await q('SELECT preferences FROM notification_preferences WHERE user_id=$1',[req.user.id]);res.json({preferences:r.rowCount?json(r.rows[0].preferences):{}})});
app.patch('/api/notification-preferences',auth,async(req,res)=>{await q('INSERT INTO notification_preferences(user_id,preferences) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET preferences=$2,updated_at=now()',[req.user.id,JSON.stringify(req.body||{})]);res.json({preferences:req.body||{}})});
app.get('/api/admin/notifications',requireAdmin,async(req,res)=>{const r=await q('SELECT n.*,u.email,u.name FROM notifications n LEFT JOIN users u ON u.id=n.user_id ORDER BY n.created_at DESC LIMIT 200');res.json({notifications:r.rows,data:r.rows})});

// MESSAGES + one-summary support
function conversationIdFor(userId){return userId;}
app.get('/api/messages',auth,async(req,res)=>{const r=await q('SELECT * FROM messages WHERE sender_id=$1 OR receiver_id=$1 ORDER BY created_at',[req.user.id]);res.json({messages:r.rows,data:r.rows})});
app.post('/api/messages',auth,async(req,res)=>{try{const text=s(req.body.message);if(!text)return res.status(400).json({error:'Message required'});const id=uid();await q('INSERT INTO messages(id,sender_id,body,severity,urgent,source,conversation_id) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,req.user.id,text,s(req.body.severity)||'normal',Boolean(req.body.urgent),s(req.body.source)||'client',req.user.id]);const r=await q('SELECT id FROM users WHERE role IN (\'owner\',\'admin\') ORDER BY role=\'owner\' DESC LIMIT 1');if(r.rowCount)await q('UPDATE messages SET receiver_id=$2 WHERE id=$1',[id,r.rows[0].id]);res.status(201).json({message:{id,body:text},ok:true})}catch(e){err(res,e,400)}});
app.get('/api/admin/messages',requireAdmin,async(req,res)=>{try{const users=await q(`SELECT u.id,u.name,u.email,u.avatar,COALESCE((SELECT body FROM messages m WHERE m.conversation_id=u.id ORDER BY m.created_at DESC LIMIT 1),'') last_message,COALESCE((SELECT created_at FROM messages m WHERE m.conversation_id=u.id ORDER BY m.created_at DESC LIMIT 1),u.created_at) last_message_at,(SELECT COUNT(*) FROM messages m WHERE m.conversation_id=u.id AND m.receiver_id=$1 AND m.read=false) unread FROM users u WHERE u.role='client' ORDER BY last_message_at DESC`,[req.user.id]);const conversations=users.rows.map(x=>({id:x.id,name:x.name,email:x.email,avatar:x.avatar,lastMessage:x.last_message,lastMessageAt:x.last_message_at,unread:Number(x.unread)}));res.json({conversations,messages:conversations,data:conversations})}catch(e){err(res,e)}});
app.get('/api/admin/messages/unread',requireAdmin,async(req,res)=>{const r=await q('SELECT COUNT(*) v FROM messages WHERE receiver_id=$1 AND read=false',[req.user.id]);res.json({unread:Number(r.rows[0].v)})});
app.get('/api/admin/messages/:id',requireAdmin,async(req,res)=>{const r=await q('SELECT * FROM messages WHERE conversation_id=$1 ORDER BY created_at',[req.params.id]);await q('UPDATE messages SET read=true WHERE conversation_id=$1 AND receiver_id=$2',[req.params.id,req.user.id]);res.json({messages:r.rows,data:r.rows})});
app.post('/api/admin/messages/:id',requireAdmin,async(req,res)=>{try{const text=s(req.body.message);if(!text)return res.status(400).json({error:'Message required'});const client=await userById(req.params.id);if(!client)return res.status(404).json({error:'Client not found'});const id=uid();await q('INSERT INTO messages(id,sender_id,receiver_id,body,severity,urgent,source,conversation_id) VALUES($1,$2,$3,$4,\'normal\',false,\'admin\',$5)',[id,req.user.id,client.id,text,client.id]);await notify(client.id,'Zhuo Support',text,'support');res.status(201).json({message:{id,body:text,senderId:req.user.id,receiverId:client.id},ok:true})}catch(e){err(res,e,400)}});

// Chatbot: creates ONE summary for the current conversation from real DB messages.
app.post('/api/chatbot',auth,async(req,res)=>{try{const text=s(req.body.message);if(text){await q('INSERT INTO messages(id,sender_id,body,severity,urgent,source,conversation_id) VALUES($1,$2,$3,$4,$5,\'chatbot\',$6)',[uid(),req.user.id,text,s(req.body.severity)||'normal',Boolean(req.body.urgent),req.user.id]);}const r=await q('SELECT body,severity,urgent,created_at FROM messages WHERE conversation_id=$1 ORDER BY created_at DESC LIMIT 50',[req.user.id]);const msgs=r.rows.reverse();const urgent=msgs.some(m=>m.urgent||m.severity==='high');const summary=msgs.length?`Résumé de la conversation : ${msgs.length} message(s) échangé(s). ${urgent?'⚠️ Une demande urgente a été détectée. ':' '}Dernier message : ${msgs[msgs.length-1].body}`:'Aucune conversation enregistrée.';res.json({reply:summary,summary,needsAdmin:urgent||msgs.length>0,conversationId:req.user.id,severity:urgent?'high':'normal'})}catch(e){err(res,e,400)}});

// STREAMING
function streamOut(r){return {id:r.id,service:r.service,name:r.name,price:Number(r.price),desc:r.description,description:r.description,active:r.active};}
app.get('/api/streaming-plans',async(req,res)=>{const r=await q('SELECT * FROM streaming_plans WHERE active=true ORDER BY service,price');const plans={netflix:r.rows.filter(x=>x.service==='netflix').map(streamOut),disney:r.rows.filter(x=>x.service==='disney').map(streamOut)};res.json(plans)});
app.get('/api/admin/streaming-plans',requireAdmin,async(req,res)=>{const r=await q('SELECT * FROM streaming_plans ORDER BY service,price');const plans={netflix:r.rows.filter(x=>x.service==='netflix').map(streamOut),disney:r.rows.filter(x=>x.service==='disney').map(streamOut)};res.json({plans,data:plans,netflix:plans.netflix,disney:plans.disney})});
app.put('/api/admin/streaming-plans',requireAdmin,async(req,res)=>{try{const plans=req.body.plans||req.body;await q('BEGIN');for(const service of ['netflix','disney']){for(const p of Array.isArray(plans[service])?plans[service]:[]){if(!p.name)continue;const id=p.id||uid();await q('INSERT INTO streaming_plans(id,service,name,price,description,active) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO UPDATE SET service=$2,name=$3,price=$4,description=$5,active=$6,updated_at=now()',[id,service,s(p.name),Number(p.price)||0,s(p.desc||p.description),p.active!==false]);}}await q('COMMIT');res.json({ok:true,plans})}catch(e){await q('ROLLBACK').catch(()=>{});err(res,e,400)}});
app.post('/api/admin/streaming-plans',requireAdmin,async(req,res)=>{try{const plans=req.body.plans||req.body;for(const service of ['netflix','disney']){for(const p of Array.isArray(plans[service])?plans[service]:[]){if(!p.name)continue;const id=p.id||uid();await q('INSERT INTO streaming_plans(id,service,name,price,description,active) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO UPDATE SET service=$2,name=$3,price=$4,description=$5,active=$6,updated_at=now()',[id,service,s(p.name),Number(p.price)||0,s(p.desc||p.description),p.active!==false]);}}res.json({ok:true,plans})}catch(e){err(res,e,400)}});
app.post('/api/streaming-orders',auth,async(req,res)=>{try{const service=s(req.body.service).toLowerCase();if(!['netflix','disney'].includes(service))return res.status(400).json({error:'Invalid streaming service'});const r=await q('INSERT INTO streaming_orders(id,customer_id,service,plan_id,plan_name,price,currency,payment_status,status,customer) VALUES($1,$2,$3,$4,$5,$6,\'USD\',\'pending\',\'Nouvelle demande\',$7) RETURNING *',[uid(),req.user.id,service,req.body.planId||null,s(req.body.planName),Number(req.body.price)||0,JSON.stringify(req.body.customer||{})]);res.status(201).json({order:r.rows[0]})}catch(e){err(res,e,400)}});
app.get('/api/streaming-orders',auth,async(req,res)=>{const r=await q('SELECT * FROM streaming_orders WHERE customer_id=$1 ORDER BY created_at DESC',[req.user.id]);res.json({orders:r.rows,data:r.rows,streamingOrders:r.rows})});
app.get('/api/admin/streaming-orders',requireAdmin,async(req,res)=>{const r=await q('SELECT so.*,u.name,u.email FROM streaming_orders so JOIN users u ON u.id=so.customer_id ORDER BY so.created_at DESC');res.json({orders:r.rows,streamingOrders:r.rows,data:r.rows})});

// TRADES
app.get('/api/trades',auth,async(req,res)=>{const r=await q('SELECT * FROM trades WHERE user_id=$1 ORDER BY created_at DESC',[req.user.id]);res.json({trades:r.rows,data:r.rows})});
app.post('/api/trades',auth,async(req,res)=>{try{const r=await q('INSERT INTO trades(id,user_id,product_id,message,device,storage,condition,wanted_product_id,images) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[uid(),req.user.id,req.body.productId||null,s(req.body.message),s(req.body.device),s(req.body.storage),s(req.body.condition),req.body.wantedProductId||null,JSON.stringify(arr(req.body.images))]);res.status(201).json({trade:r.rows[0]})}catch(e){err(res,e,400)}});

// SUPPORT CONFIG
app.get('/api/support/config',async(req,res)=>{const r=await q("SELECT value FROM app_settings WHERE key='support'");const v=r.rowCount?json(r.rows[0].value):{};res.json({enabled:v.enabled!==false,whatsapp:v.whatsapp||process.env.ADMIN_WHATSAPP||''})});
app.get('/api/admin/settings/support',requireAdmin,async(req,res)=>{const r=await q("SELECT value FROM app_settings WHERE key='support'");res.json({settings:r.rowCount?json(r.rows[0].value):{enabled:true,whatsapp:process.env.ADMIN_WHATSAPP||''}})});
app.patch('/api/admin/settings/support',requireAdmin,async(req,res)=>{const value={enabled:req.body.enabled!==false,whatsapp:s(req.body.whatsapp)||process.env.ADMIN_WHATSAPP||''};await q("INSERT INTO app_settings(key,value) VALUES('support',$1) ON CONFLICT(key) DO UPDATE SET value=$1,updated_at=now()",[JSON.stringify(value)]);res.json({settings:value})});

// PUSH
app.get('/api/push/public-key',(req,res)=>res.json({publicKey:process.env.PUSH_PUBLIC_KEY||''}));
app.post('/api/push/subscribe',auth,async(req,res)=>{if(!req.body?.endpoint)return res.status(400).json({error:'Push subscription required'});await q('INSERT INTO push_subscriptions(id,user_id,subscription) VALUES($1,$2,$3) ON CONFLICT(user_id) DO UPDATE SET subscription=$3,updated_at=now()',[uid(),req.user.id,JSON.stringify(req.body)]);res.json({ok:true})});
app.delete('/api/push/subscribe',auth,async(req,res)=>{await q('DELETE FROM push_subscriptions WHERE user_id=$1',[req.user.id]);res.json({ok:true})});

// PAYPAL REAL REST API. No frontend secret. Orders remain pending until PayPal capture succeeds.
async function paypalToken(){if(!process.env.PAYPAL_CLIENT_ID||!process.env.PAYPAL_CLIENT_SECRET)throw Object.assign(new Error('PayPal is not configured on the backend.'),{status:503});const base=String(process.env.PAYPAL_MODE).toLowerCase()==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com';const token=Buffer.from(`${process.env.PAYPAL_CLIENT_ID}:${process.env.PAYPAL_CLIENT_SECRET}`).toString('base64');const r=await fetch(`${base}/v1/oauth2/token`,{method:'POST',headers:{Authorization:`Basic ${token}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});const d=await r.json();if(!r.ok)throw new Error(d.error_description||'PayPal authentication failed');return {base,access:d.access_token};}
app.post('/api/payments/paypal/create-order',auth,async(req,res)=>{try{const pp=await paypalToken();const c=await pool.connect();try{await c.query('BEGIN');const {out,total,currency}=await cartPriced(c,req.body.items||[]);const internal=uid();await c.query('INSERT INTO orders(id,customer_id,items,total,currency,payment_method,payment_status,status) VALUES($1,$2,$3,$4,$5,\'PayPal\',\'pending\',\'En attente\')',[internal,req.user.id,JSON.stringify(out),total,currency]);const amount=total.toFixed(2);const r=await fetch(`${pp.base}/v2/checkout/orders`,{method:'POST',headers:{Authorization:`Bearer ${pp.access}`,'Content-Type':'application/json'},body:JSON.stringify({intent:'CAPTURE',purchase_units:[{reference_id:internal,amount:{currency_code:process.env.PAYPAL_CURRENCY||currency||'USD',value:amount}}],application_context:{user_action:'PAY_NOW',return_url:`${process.env.FRONTEND_ORIGIN||''}/?paypal=success`,cancel_url:`${process.env.FRONTEND_ORIGIN||''}/?paypal=cancel`}})});const d=await r.json();if(!r.ok)throw new Error(d.message||'PayPal order creation failed');await c.query('COMMIT');res.status(201).json({id:d.id,orderId:d.id,paypalOrderId:d.id,internalOrderId:internal,approveUrl:d.links?.find(x=>x.rel==='approve')?.href||'',links:d.links||[]});}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e}finally{c.release();}}catch(e){err(res,e,e.status||400)}});
app.post('/api/payments/paypal/capture',auth,async(req,res)=>{try{const paypalId=s(req.body.paypalOrderId||req.body.orderId);if(!paypalId)return res.status(400).json({error:'PayPal order ID required'});const pp=await paypalToken();const r=await fetch(`${pp.base}/v2/checkout/orders/${encodeURIComponent(paypalId)}/capture`,{method:'POST',headers:{Authorization:`Bearer ${pp.access}`,'Content-Type':'application/json'}});const d=await r.json();if(!r.ok)throw new Error(d.message||'PayPal capture failed');if(d.status!=='COMPLETED')return res.status(409).json({error:'PayPal payment is not completed',paypalStatus:d.status});const internal=s(req.body.orderId);let oid=internal;if(!oid){const ref=d.purchase_units?.[0]?.reference_id;oid=ref||'';}if(!oid)return res.status(400).json({error:'Internal order reference missing'});const o=await q('SELECT * FROM orders WHERE id=$1 AND customer_id=$2',[oid,req.user.id]);if(!o.rowCount)return res.status(404).json({error:'Internal order not found'});const items=json(o.rows[0].items)||[];const c=await pool.connect();try{await c.query('BEGIN');for(const item of items){const sr=await c.query('UPDATE products SET stock=stock-$2,quantity=stock-$2,updated_at=now() WHERE id=$1 AND stock >= $2',[item.productId,Number(item.quantity)||1]);if(!sr.rowCount)throw new Error('Stock changed; payment cannot be completed safely.');}await c.query('UPDATE orders SET payment_status=\'paid\',status=\'Confirmée\',updated_at=now() WHERE id=$1',[oid]);await c.query('COMMIT');await notify(req.user.id,'Paiement PayPal confirmé',`Commande ${oid} payée avec succès.`,'payment');res.json({ok:true,status:'COMPLETED',orderId:oid,paypalOrderId:paypalId,paypal:d})}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e}finally{c.release()}}catch(e){err(res,e,e.status||400)}});

// Friendly aliases used by older frontend patches
app.post('/api/payments/paypal/capture-order',(req,res)=>{req.url='/api/payments/paypal/capture';return app._router.handle(req,res,()=>{})});

app.use((req,res)=>res.status(404).json({error:'Route not found',path:req.path,method:req.method}));
app.use((e,req,res,next)=>{console.error(e);res.status(500).json({error:'Server error'});});

async function init(){if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is required');const fs=await import('fs/promises');await q(await fs.readFile(new URL('./schema.sql',import.meta.url),'utf8'));await q("ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar text");await q("ALTER TABLE products ADD COLUMN IF NOT EXISTS old_price numeric(12,2) DEFAULT 0");await q("ALTER TABLE products ADD COLUMN IF NOT EXISTS discount numeric(8,2) DEFAULT 0");await q("ALTER TABLE products ADD COLUMN IF NOT EXISTS images jsonb NOT NULL DEFAULT '[]'");await q("ALTER TABLE products ADD COLUMN IF NOT EXISTS quantity integer NOT NULL DEFAULT 0");await q("ALTER TABLE products ADD COLUMN IF NOT EXISTS storage jsonb NOT NULL DEFAULT '[]'");await q("ALTER TABLE products ADD COLUMN IF NOT EXISTS colors jsonb NOT NULL DEFAULT '[]'");await q("ALTER TABLE products ADD COLUMN IF NOT EXISTS specifications jsonb NOT NULL DEFAULT '{}'");await q("ALTER TABLE products ADD COLUMN IF NOT EXISTS published boolean NOT NULL DEFAULT true");await q("ALTER TABLE promotions ADD COLUMN IF NOT EXISTS price numeric(12,2) DEFAULT 0");await q("ALTER TABLE promotions ADD COLUMN IF NOT EXISTS old_price numeric(12,2) DEFAULT 0");await q("ALTER TABLE promotions ADD COLUMN IF NOT EXISTS discount numeric(8,2) DEFAULT 0");await q("ALTER TABLE promotions ADD COLUMN IF NOT EXISTS images jsonb NOT NULL DEFAULT '[]'");await q("ALTER TABLE promotions ADD COLUMN IF NOT EXISTS product_id uuid");
 if(process.env.OWNER_EMAIL&&process.env.OWNER_PASSWORD){const email=s(process.env.OWNER_EMAIL).toLowerCase();const r=await q('SELECT id,role FROM users WHERE lower(email)=lower($1)',[email]);if(!r.rowCount){await q('INSERT INTO users(id,email,password_hash,name,role) VALUES($1,$2,$3,$4,\'owner\')',[uid(),email,await bcrypt.hash(process.env.OWNER_PASSWORD,12),s(process.env.OWNER_NAME)||'ZhuoMarket Owner']);}else if(r.rows[0].role!=='owner')await q("UPDATE users SET role='owner',updated_at=now() WHERE id=$1",[r.rows[0].id]);}}
init().then(()=>app.listen(PORT,()=>console.log(`ZhuoMarket backend v3.0.0 listening on ${PORT}`))).catch(e=>{console.error('BOOT ERROR',e);process.exit(1)});
